Repository Skript-MC/Swan, pull requests merged in 2021-01, with the labels that each got.

#121 Ajout d'un argument à la commande .code
  src/commands/basic/code.js
Labels: enhancement

#124 Fix système anti liens de doc
  config/settings.ts
  src/listeners/client/message.ts
  src/listeners/client/messageUpdate.ts
Labels: enhancement, v2

#126 Ajout des messages
  config/commands/basic.ts
  src/commands/basic/addonPack.ts
  src/commands/basic/autoMessage.ts
  src/commands/basic/errorDetails.ts
  src/models/message.ts
  src/types/CommandArguments.ts
  src/types/index.ts
  src/utils/index.ts
  src/utils/searchMessageSimilarity.ts
Labels: enhancement, v2

#127 ✨ Introducing forum feed
  .env.example
  config/settings.ts
  config/tasks.ts
  package-lock.json
  package.json
  src/tasks/forumFeed.ts
  src/types/index.ts
Labels: feature, v2
